- id: '1583519290480'
  alias: Coming Home - Travis
  description: ''
  trigger:
  - entity_id: person.travis_lonergan
    event: enter
    platform: zone
    zone: zone.home_small
  condition: []
  action:
  - device_id: 38c69b3c357a4efd87a5c0e0b7e2474a
    domain: switch
    entity_id: switch.porch
    type: turn_on
  - device_id: ba3750db9274455388311e2a32ab6f35
    domain: light
    entity_id: light.lamp_switch_level
    type: turn_on
- id: '1583897249203'
  alias: Ensure Living Room Entertainment on
  description: ''
  trigger:
  - device_id: 4ddbbe8870744afba0b009d5e93093a5
    domain: switch
    entity_id: switch.fibaro_system_unknown_type_1401_id_2000_switch_2
    platform: device
    type: turned_off
  condition: []
  action:
  - device_id: 4ddbbe8870744afba0b009d5e93093a5
    domain: switch
    entity_id: switch.fibaro_system_unknown_type_1401_id_2000_switch_2
    type: turn_on
- id: '1583897395463'
  alias: Living Room Lamp On - TV Off Trigger
  description: ''
  trigger:
  - below: 100
    device_id: 4ddbbe8870744afba0b009d5e93093a5
    domain: sensor
    entity_id: sensor.fibaro_system_unknown_type_1401_id_2000_power
    platform: device
    type: value
  condition:
  - after: sunset
    condition: sun
  - condition: device
    device_id: ba3750db9274455388311e2a32ab6f35
    domain: light
    entity_id: light.lamp_switch_level
    type: is_on
  action:
  - scene: scene.occupied_living_room
- id: '1583983932968'
  alias: Coming Home - Becky
  description: ''
  trigger:
  - entity_id: person.becky_lonergan
    event: enter
    platform: zone
    zone: zone.home_small
  condition: []
  action:
  - device_id: ba3750db9274455388311e2a32ab6f35
    domain: light
    entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level
    type: turn_on
  - device_id: b9f50c93f36c4425809243bbee8c8167
    domain: switch
    entity_id: switch.porch
    type: turn_on
- id: '1584497519601'
  alias: Living Room Empty
  description: ''
  trigger:
  - device_id: f91ff92073684805bc76f70edfab3a27
    domain: binary_sensor
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor_2
    for:
      hours: 0
      minutes: 10
      seconds: 0
    platform: device
    type: turned_on
  - device_id: 4cb9f6acbe3c4b82bfbb8fdaa2419442
    domain: binary_sensor
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor
    for:
      hours: 0
      minutes: 10
      seconds: 0
    platform: device
    type: turned_off
  condition:
  - condition: device
    device_id: 4cb9f6acbe3c4b82bfbb8fdaa2419442
    domain: binary_sensor
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
    type: is_off
  - condition: device
    device_id: f91ff92073684805bc76f70edfab3a27
    domain: binary_sensor
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor_2
    type: is_off
  action:
  - scene: scene.dark_living_room
- id: '1584820541363'
  alias: Washer Done
  description: ''
  trigger:
  - device_id: 247240f6128c4bb598f89ec3c358db01
    domain: binary_sensor
    entity_id: binary_sensor.vision_security_zs5101_shock_and_vibration_sensor_sensor
    platform: device
    type: turned_off
  condition: []
  action:
  - data:
      message: Washer is done. Washer is done
    service: tts.google_translate_say
- id: '1585658717408'
  alias: Living Room Occupied - TV Off
  description: ''
  trigger:
  - device_id: 4cb9f6acbe3c4b82bfbb8fdaa2419442
    domain: binary_sensor
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor
    platform: device
    type: turned_on
  - device_id: f91ff92073684805bc76f70edfab3a27
    domain: binary_sensor
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor_2
    platform: device
    type: turned_on
  condition:
  - below: 100
    condition: device
    device_id: 4ddbbe8870744afba0b009d5e93093a5
    domain: sensor
    entity_id: sensor.fibaro_system_unknown_type_1401_id_2000_power
    type: is_value
  action:
  - scene: scene.occupied_living_room
  mode: single
- id: '1585664417789'
  alias: Living Room Occupied - TV On
  description: ''
  trigger:
  - device_id: f91ff92073684805bc76f70edfab3a27
    domain: binary_sensor
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor_2
    for:
      hours: 0
      minutes: 0
      seconds: 10
    platform: device
    type: turned_on
  - device_id: 4cb9f6acbe3c4b82bfbb8fdaa2419442
    domain: binary_sensor
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 10
    platform: device
    type: turned_on
  condition:
  - above: 100
    condition: device
    device_id: 4ddbbe8870744afba0b009d5e93093a5
    domain: sensor
    entity_id: sensor.fibaro_system_unknown_type_1401_id_2000_power
    type: is_value
  - condition: device
    device_id: ba3750db9274455388311e2a32ab6f35
    domain: light
    entity_id: light.lamp_switch_level
    type: is_off
  action:
  - scene: scene.theater_motion
- id: '1585664770269'
  alias: Sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - scene: scene.evening
- id: '1585664894691'
  alias: Sunrise
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - scene: scene.morning
- id: '1586035770251'
  alias: TV On
  description: ''
  trigger:
  - above: 100
    device_id: 4ddbbe8870744afba0b009d5e93093a5
    domain: sensor
    entity_id: sensor.fibaro_system_unknown_type_1401_id_2000_power
    platform: device
    type: value
  condition:
  - condition: device
    device_id: ba3750db9274455388311e2a32ab6f35
    domain: light
    entity_id: light.lamp_switch_level
    type: is_on
  action:
  - scene: scene.theater_motion
- id: '1586036073787'
  alias: Late Night
  description: ''
  trigger:
  - event: sunset
    offset: 03:00:00
    platform: sun
  condition: []
  action:
  - scene: scene.late_night
- id: '1590274083091'
  alias: TV On And Lamp On
  description: ''
  trigger:
  - below: 100
    device_id: 4ddbbe8870744afba0b009d5e93093a5
    domain: sensor
    entity_id: sensor.fibaro_system_unknown_type_1401_id_2000_power
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: value
  condition:
  - condition: device
    device_id: ba3750db9274455388311e2a32ab6f35
    domain: light
    entity_id: light.lamp_switch_level
    type: is_on
  action:
  - scene: scene.occupied_living_room
  mode: single
