- id: 'occupied-living-room'
  name: Occupied Living Room
  entities:
    light.lamp_switch_level:
      brightness: 255
      state: 'on'
- id: 'theater-motion'
  name: Theater Motion
  entities:
    light.lamp_switch_level:
      brightness: 40
      state: 'on'
- id: 'dark-living-room'
  name: Dark Living Room
  entities:
    light.lamp_switch_level:
      state: 'off'
- id: 'evening'
  name: Evening
  entities:
    switch.porch:
      state: 'on'
    switch.back_porch_north:
      state: 'on' 
    switch.back_porch_south:
      state: 'on'
- id: 'late_night'
  name: Late Night
  entities:
    switch.porch:
      state: 'on'
    switch.back_porch_north:
      state: 'off' 
    switch.back_porch_south:
      state: 'off'
- id: 'morning'
  name: Morning
  entities:
    switch.porch:
      state: 'off'
    switch.back_porch_north:
      state: 'off'
    switch.back_porch_south:
      state: 'off'
